// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk-QCJYP59ltV7R7-GDAsQl1WYOFcCSEM',
    appId: '1:1069072473692:web:a4b1c71969d14231405099',
    messagingSenderId: '1069072473692',
    projectId: 'projetobiblioteca-477e4',
    authDomain: 'projetobiblioteca-477e4.firebaseapp.com',
    storageBucket: 'projetobiblioteca-477e4.firebasestorage.app',
    measurementId: 'G-QL1CCEVB56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaPx4Cq6c9kD_QMsJna7HG3ImRTkxU7zk',
    appId: '1:1069072473692:android:11d1b2647abea342405099',
    messagingSenderId: '1069072473692',
    projectId: 'projetobiblioteca-477e4',
    storageBucket: 'projetobiblioteca-477e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8lU1j-YGybWlgtj6_8o6h05equNUgS4c',
    appId: '1:1069072473692:ios:abdfa3f2b3608895405099',
    messagingSenderId: '1069072473692',
    projectId: 'projetobiblioteca-477e4',
    storageBucket: 'projetobiblioteca-477e4.firebasestorage.app',
    iosClientId: '1069072473692-l422a5t1mrjuak3i5soaq7v85dd7mbmc.apps.googleusercontent.com',
    iosBundleId: 'com.example.biblioteca',
  );
}
